version: "3.8"
services:
  notes-api:
    container_name: notes-api
    restart: always
    build: ./notes-api
    env_file: .env
    environment:
      - PORT=$PORT
      - MONGO_URL=$MONGO_URL
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27100:27017"
    volumes:
      - ./docker-root/mongobackup:/mongobackup
      - ./docker-root/mongo-data:/data/db
  notes-ui:
    container_name: notes-ui
    restart: always
    build: ./notes-ui
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./notes-ui:/apps/notes-ui
    links:
      - notes-api
